### ISSUE TITLE
[Suggestion] Possible to re-introduce the % probability for a ruined orgasm?

### ISSUE THREAD

**Issue by gemini92** [thefapinstructor/fapinstructor#46]
I understand it used to be possible to specify the probability of a ruined orgasm if we selected the option of having a "ruined orgasm" in the fapinstructor interface. Right now, it seems like it is no longer possible to do so. Any chance if it would be possible to re-introduce such a feature?

Thanks once again for this great application :)

**Comment by The1nstructor** [comment]
Maybe I could introduce something like that with the newest update I am working on. But don’t expect that before early November.

**Comment by gemini92** [comment]
Haha thanks. Will be looking forward to it
