### ISSUE TITLE
Red Light Green Light not working when changing slowest / fastest stroke speed

### ISSUE THREAD

**Issue by LenAnderson** [thefapinstructor/fapinstructor#57]
When changing the fastest or slowest stroke speeds `store.config.fastestStrokeSpeed` and `store.config.slowestStrokeSpeed` are stored as strings and the result of `getAverageStrokeSpeed()` is `NaN`. This leads to a "green light" speed of 0.  Don't know if this affects other parts as well.

![Imgur](https://i.imgur.com/rzM29UP.png)

![Imgur](https://i.imgur.com/AEIKNcS.png)

![Imgur](https://i.imgur.com/clBy1nX.png)

**Comment by The1nstructor** [comment]
I think this is not intended. I already had similar bugs with several other tasks. 

Every time a access to `store.config.*` is done I had to add a `parseInt(store.config.*, 10)` call.

Do you think there is a better way? Maybe one could store these values directly as Integers? I'm not so familiar with JavaScript unfortunately 😉

**Comment by The1nstructor** [comment]
For example #49 take a look at the commit there

**Comment by LenAnderson** [comment]
the values should be stored as its or floats and as far as JavaScript is concerned that's easy. Have to dig through the code to see how the values are bound and which of the ten thousand nested dependencies is responsible :D

**Comment by The1nstructor** [comment]
Yeahhhh! 

I mean the store gets initialized in the file configureStore.js ... maybe one could declare a type or something there?
