### ISSUE TITLE
Suggestion: Add a way to activate edge with a keyboard shorcut + Minimalistic voices.

### ISSUE THREAD

**Issue by Fuzen777** [thefapinstructor/fapinstructor#9]
That would allow more flexibility with multi-tabbing since you wouldn't have to go back to FI to press the button — and then actually pressing it may be a challenge in itself. Thus a shortcut. If global, it would be even better since it won't require any direct interaction. 

The minimalistic voices would be here to tell the user about the edging start/hold/end only when they have the app in background. (Maybe Green/Red light too?)

**Comment by thefapinstructor** [comment]
Added an option to disable the extra moans and voice on the HUD page instead of the config page so they can be toggled on and off during game play.

The ability to have a global hotkey isn't possible as browsers prevent this.
